# Generated by Django 3.2.7 on 2021-11-04 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelesCore', '0002_auto_20211104_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='cama',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='cocina',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='desayuno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='lavanderia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='personas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='roomtype',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='begin_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 521048)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 521048)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 521048)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 517049)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 517049)),
        ),
        migrations.AlterField(
            model_name='room',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 520049)),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 4, 17, 58, 51, 520049)),
        ),
    ]
