# Generated by Django 3.2.9 on 2021-11-25 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelesCore', '0003_auto_20211124_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='begin_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 996454)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 996454)),
        ),
        migrations.AlterField(
            model_name='booking',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 996454)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 995454)),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 995454)),
        ),
        migrations.AlterField(
            model_name='room',
            name='crated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 996454)),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 24, 23, 19, 51, 996454)),
        ),
    ]
